#!/bin/bash

HOME=`pwd`
DEST="nearlyfreemouse_static.`uname -p`.`date +%C%y%m%d`.tgz"

rm -rf /tmp/nfms
mkdir /tmp/nfms

cd ${HOME}/../
tar -zcf /tmp/nfms/nfm.tgz nearlyfreemouse
cd /tmp/nfms

tar -zxf nfm.tgz
apt-get source libxdo2


cd xdotool-2.20110530.1
make libxdo.a
cp libxdo.a ../nearlyfreemouse
cd ../nearlyfreemouse

make nearlyfreemouse.static
cd ../

tar -zcf ${DEST} nearlyfreemouse/nearlyfreemouse nearlyfreemouse/nearlyfreemouse.autostart nearlyfreemouse/nearlyfreemouse.desktop

